#!/usr/bin/env bash
# displays:
#   - the content of the currrent directory
#   - in a list format
#   - where only the part of the name after the first dash is diplayed

for file in *
do
  echo "$file" | cut -d'-' -f2
done
