#!/usr/bin/env bash
# configures an ubuntu server

cp /etc/hosts draft
sed -i 's/^127\.0\.0\.1\(.*\)localhost$/127.0.0.2\1localhost/g' draft
sed -i '/^127\.0\.0\.2.*localhost$/a\8.8.8.8         facebook.com' draft
cp draft /etc/hosts
rm draft
